// <auto-generated />
namespace DirecTvGo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_idPhone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_idPhone));
        
        string IMigrationMetadata.Id
        {
            get { return "202110041428576_add_idPhone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
